<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dalam Masa Pengerjaan</name>
   <tag></tag>
   <elementGuidId>dc509f9a-e02f-46df-b789-f367bbfc3499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-1y4jycc.r-wgabs5.r-1loqt21.r-1pi2tsx.r-1777fci.r-1fz3rvf.r-1otgn73.r-eafdt9.r-1i6wzkk.r-lrvibr > div.css-901oao</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e400cd2-fca3-4875-80ad-a47bb9ac8173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2e9ca081-1faf-4bae-8bf9-d69e3a1e7aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao</value>
      <webElementGuid>e7807f62-5f26-4071-a2a6-a0387af26766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dalam Masa Pengerjaan</value>
      <webElementGuid>c44733be-fc0b-46ea-8db6-f45d72424cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-bsco3b r-13awgt0 r-1tsuqlv r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-14lw9ot r-zxcyg9 r-1quu1zo r-18u37iz r-1ph75f1 r-1wtj0ep r-1guathk r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1pi2tsx&quot;]/div[@class=&quot;css-1dbjc4n r-1y4jycc r-wgabs5 r-1loqt21 r-1pi2tsx r-1777fci r-1fz3rvf r-1otgn73 r-eafdt9 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-901oao&quot;]</value>
      <webElementGuid>bb895250-2920-4521-a003-8da8d50d43ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>1f026451-5c96-4fdc-a7d4-0f1f7005e435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Data'])[1]/following::div[2]</value>
      <webElementGuid>75e83602-67ab-44f9-8700-6709a633e0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi TOKO'])[1]/following::div[5]</value>
      <webElementGuid>4a40cff7-44ef-4b22-8cef-838e6573d1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dewi'])[1]/preceding::div[1]</value>
      <webElementGuid>b93d0d4c-9c6b-42bd-8626-1991c6d195e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dalam Masa Pengerjaan']/parent::*</value>
      <webElementGuid>6ecda0da-7647-42cc-b93a-cd033e835cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>ba2ca360-6a56-4d98-8ba0-be8303386304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dalam Masa Pengerjaan' or . = 'Dalam Masa Pengerjaan')]</value>
      <webElementGuid>10f2f278-0018-4177-9052-f1c8980767c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
