<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Klaim</name>
   <tag></tag>
   <elementGuidId>b1d3f01e-4d17-490b-b1f2-3b702f89beaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/table/tbody/tr/td[9]/div/button/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.jss120.jss122.MuiButton-disableElevation > span.MuiButton-label > div.css-901oao</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c61291b7-72fc-416a-afe7-fc9896718dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5fc3d45a-2581-41ac-93ab-b0ce7deacf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao</value>
      <webElementGuid>8509a912-0f89-4e60-aa18-9b0544dc3b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Klaim</value>
      <webElementGuid>32a61d20-0aad-423c-a676-f3a4c0cc2e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-bsco3b r-13awgt0 r-1tsuqlv r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-150rngu r-eqz5dr r-16y2uox r-1wbh5a2 r-11yh6sk r-1rnoaur r-1sncvnh&quot;]/div[@class=&quot;css-1dbjc4n r-bsco3b r-13awgt0 r-11yd5a9 r-1h4fu65&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;MuiTableContainer-root jss239&quot;]/table[@class=&quot;MuiTable-root jss238&quot;]/tbody[@class=&quot;MuiTableBody-root&quot;]/tr[@class=&quot;MuiTableRow-root jss241&quot;]/td[@class=&quot;MuiTableCell-root jss240 MuiTableCell-body MuiTableCell-sizeSmall&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text jss120 jss122 MuiButton-disableElevation&quot;]/span[@class=&quot;MuiButton-label&quot;]/div[@class=&quot;css-901oao&quot;]</value>
      <webElementGuid>9f98b3a2-e35a-43a9-a7ce-0fa914ea9ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/table/tbody/tr/td[9]/div/button/span/div</value>
      <webElementGuid>523d8116-78f1-43ee-83ec-03977f8695a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unverified'])[1]/following::div[2]</value>
      <webElementGuid>7a476a75-6e5c-4b5a-9c3e-a5dc32d285be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[3]</value>
      <webElementGuid>4f461674-368d-406d-b6c7-9dbe773e3af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tb multi jaya'])[1]/preceding::div[1]</value>
      <webElementGuid>58f9edaf-98a3-4236-bd97-d8ae1e18acc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KALIMANTAN BARAT'])[1]/preceding::div[3]</value>
      <webElementGuid>429ba33f-568e-43e7-9021-4451f8ee29c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Klaim']/parent::*</value>
      <webElementGuid>08dab02d-550b-4e5b-9785-f30e4a3f717a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/button/span/div</value>
      <webElementGuid>a0946bf9-9740-43f7-ab91-9968a1baddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Klaim' or . = 'Klaim')]</value>
      <webElementGuid>48694c1c-1aaf-4a15-bf63-580242244147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
