<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Initial_Initial</name>
   <tag></tag>
   <elementGuidId>3d7c9f21-2d6c-4495-a239-b177d9c17a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Initial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Initial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5391e0a-a4ea-43d3-844c-bfdb01b172eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Initial</value>
      <webElementGuid>383263a5-f0a2-4e7b-827b-dbb77953c532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Initial</value>
      <webElementGuid>d1a706c1-b671-4a05-b1c4-1280f5ba4209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a696955-6f85-4545-ad3d-b317055aaad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Initial&quot;)</value>
      <webElementGuid>a2c0815a-6994-4fa1-9623-711f9f2d613f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Initial']</value>
      <webElementGuid>b2e92155-cd40-4ccb-87c1-1e45b769488b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='details']/table/tbody/tr[2]/td[2]/span/input</value>
      <webElementGuid>712e2b54-162d-4f3b-b603-9f6ad5421c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e54ba7e1-c69b-41ae-bb35-3c1849870442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Initial' and @name = 'Initial' and @type = 'text']</value>
      <webElementGuid>4ebdbd64-9d1b-4f21-8c80-ae1a0bdc0f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
