<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_MiddleName</name>
   <tag></tag>
   <elementGuidId>1346af17-0dfd-4412-ae61-90d4dc11ae5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MiddleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MiddleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a25648d-f510-44da-9a60-29569c78c69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MiddleName</value>
      <webElementGuid>963d8283-ca2f-4a78-90a6-7833ee0a5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MiddleName</value>
      <webElementGuid>7518d218-5563-4dd6-906e-1bcbab886930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fddd4e7-0fa6-48a2-96ae-f88683e0a168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MiddleName&quot;)</value>
      <webElementGuid>1578105f-7df6-4e4a-a1bf-ebe22089399b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MiddleName']</value>
      <webElementGuid>4dbcf767-8bda-4dd2-8280-f09f30e23da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='details']/table/tbody/tr[4]/td[2]/span/input</value>
      <webElementGuid>cc826807-31b4-4399-b022-cdabd05ac444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/span/input</value>
      <webElementGuid>89adbeb1-0022-406d-b75a-a971f02e74fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MiddleName' and @name = 'MiddleName' and @type = 'text']</value>
      <webElementGuid>69751aff-747a-4307-ad8a-3a377ea8ed93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
