<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectMr.Ms</name>
   <tag></tag>
   <elementGuidId>f2093614-823f-4b4a-9755-ee763b3b48bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TitleId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TitleId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>466ced0e-6e62-4889-a831-d51743ef68a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b4301cd-9d91-47e8-9098-72f0dd582f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field TitleId must be a number.</value>
      <webElementGuid>d9395ae4-6d05-4421-87a8-b2230e614252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TitleId</value>
      <webElementGuid>6f2ece7c-6b37-43bb-846f-f1b0bc4464d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TitleId</value>
      <webElementGuid>6d821e3f-ab4e-42c8-9c50-697f94c12bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectMr.Ms. </value>
      <webElementGuid>8e1dfef0-97fc-4a97-b898-23b9c36f45ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TitleId&quot;)</value>
      <webElementGuid>13dc953d-97aa-4d46-86c2-418133b91d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TitleId']</value>
      <webElementGuid>e109ffbd-242f-413a-8217-27309f31cd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='details']/table/tbody/tr/td[2]/span/select</value>
      <webElementGuid>c2f1f5d1-3491-4f9a-a288-204e4770459f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>9fc65de3-bd8e-49f2-aaf4-7f4047b874b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial'])[1]/preceding::select[1]</value>
      <webElementGuid>f477e86a-52af-44cc-adb6-27f022522265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a04d03bd-7cfe-4e56-9836-fbcdb7dff9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TitleId' and @name = 'TitleId' and (text() = 'SelectMr.Ms. ' or . = 'SelectMr.Ms. ')]</value>
      <webElementGuid>d4fbcd99-823d-4d14-b30b-e36bd89ea69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
